name: Release Binary
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get go mod info
        id: gomod
        uses: pawndev/go-modfile-information@v1.1.0
        with:
          modfile: go.mod # optional default to `go.mod`

      - uses: actions/setup-go@v5
        with:
          go-version: "${{ steps.gomod.outputs.go_version }}"

#      - name: Login to Registry
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"